[package]
name = "virtual-lorawan-device"
version = "0.1.0"
authors = ["lthiery <thiery.louis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1"
env_logger = "0"
log = "0"
lorawan-encoding = { git = "https://github.com/ivajloip/rust-lorawan.git" }
lorawan-device = { git = "https://github.com/ivajloip/rust-lorawan.git" }
semtech-udp = { version = "0.5", features = ["client"] }
heapless = "0.7"

structopt = "*"
thiserror = "1"
rand = "*"

[dependencies.tokio]
version = "1"
features = ["macros", "sync", "time", "rt-multi-thread"]

[features]
abp = []