# Optionally override host IP
[packet_forwarder.default]
host = "127.0.0.1:1689" # gateway-rs listening port



[device.one.credentials]
# Must register an OTAA device on the things network to get app_eui, dev_eui and app_key
dev_eui = "6081F9C2F457D396"   
app_eui = "6081F9C2627E358C"
app_key = "15C75F161C63DDFB1F07797380B3321A"
